Waybar Template Pattern and Global Color Config
- Created a abs class to store colors.
- Created a templating pattern for waybar to use global colors
- Created a decent makefile with dependency tree.
- Will use same templating pattern for other config files in future
  commits.

diff --git a/waybar/Makefile b/waybar/Makefile
--- a/waybar/Makefile
+++ b/waybar/Makefile
@@ -1,12 +1,43 @@
-.PHONY: install
+.DEFAULT_GLOBAL := config-install
 
-WAYBAR_DIR := ~/.config/waybar
+WAYBAR_DIR := $(HOME)/.config/waybar
 
-install:
-	mkdir -p $(WAYBAR_DIR)
-	cp -v config.jsonc $(WAYBAR_DIR)
-	cp -v style.css $(WAYBAR_DIR)
+# Phony Targets
+.PHONY: all waybar-installed config-install get-deps
+all: waybar-installed get-deps config-install
 
-.PHONY: get-deps
-get-deps:
-	sudo pacman -S waybar
+get-deps: check-venv
+	@pip install -r requirements.txt
+
+waybar-installed:
+	@if ! command -v waybar > /dev/null; then \
+		echo "Error: could not find waybar"; \
+		exit 1; \
+	fi
+
+check-venv:
+	@if [ -z "$$VIRTUAL_ENV" ] && [ -z "$$CONDA_PREFIX" ]; then \
+		echo "Error: Not inside a Python virtual environment"; \
+		exit 1; \
+	fi
+
+config-install: $(WAYBAR_DIR)/style.css $(WAYBAR_DIR)/config.jsonc
+
+# Targets:
+./build:
+	@mkdir -p ./build/
+
+build/style.css: check-venv ./build
+	@python3 gen_style.py
+
+build/config.jsonc: check-venv ./build
+	@python3 gen_config.py
+
+$(WAYBAR_DIR):
+	@mkdir -p $(WAYBAR_DIR)
+
+$(WAYBAR_DIR)/style.css: $(WAYBAR_DIR) build/style.css
+	@cp -v build/style.css $(WAYBAR_DIR)
+
+$(WAYBAR_DIR)/config.jsonc: $(WAYBAR_DIR) build/config.jsonc
+	@cp -v build/config.jsonc $(WAYBAR_DIR)
